---
# https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst
# curl -sSL https://api.github.com/repos/aws/aws-cli/tags
aws_cli:
  src: /opt/src/awscli

# https://github.com/99designs/aws-vault/releases
aws_vault:
  revision: v7.2.0

# https://github.com/docker/compose/releases
docker_compose:
  revision: v2.18.1

# https://github.com/docker/buildx/releases
docker_buildx:
  revision: v0.11.2

# https://github.com/elm/compiler/releases
elm:
  revision: 0.19.1

# https://github.com/JetBrains/JetBrainsMono/releases
jetbrains_mono:
  revision: "2.304"
  prefix: /usr/local/share/fonts/jetbrains-mono

# https://github.com/neovim/neovim/releases
neovim:
  version: v0.9.4

# https://github.com/erlang/rebar3/releases
rebar3:
  revision: 3.22.1
  src: /opt/src/rebar3

# https://github.com/darktable-org/darktable/releases
# https://github.com/yowcow/darktable-deb/releases
yowcow_darktable:
  revision: 4.4.2-3

# https://github.com/erlang/otp/releases
# https://github.com/yowcow/erlang-deb/releases
yowcow_erlang:
  revision: 26.1.2-1

# https://github.com/swaywm/sway/releases
# https://github.com/yowcow/swaywm-deb/releases
yowcow_sway:
  revision:
    sway: 1.8.1-2
    wlroots: 0.16.2-2
