---
users: []

ufw:
  default: reject
  logging: low
  rules:
    - to_port: 22
      rule: allow
    - to_port: 80
      rule: allow
    - to_port: 443
      rule: allow
    - to_port: 2222
      rule: allow
    - to_port: 6697
      rule: allow
