---
- name: apply configuration to all nodes
  hosts: all
  become: yes
  gather_facts: no
  roles:
    ## environment
    - apt
    - common
    - journald
    - ufw
    - users
    ## compilers/runtimes
    - docker
    - elm
    - erlang
    - haskell
    - nodejs
    - perl
    - php
    - podman
    - python
    ## tools/apps
    - aws
    - neovim
    - protobuf

- name: apply configuration to laptop
  hosts: laptop
  become: yes
  gather_facts: no
  roles:
    - bluetooth
    - desktop
    - darktable
    - fonts
    - wezterm

- name: apply configuration to development
  hosts: development
  become: yes
  gather_facts: no
  roles:
    - grub

- name: apply configuration to production
  hosts: production
  become: yes
  gather_facts: no
  roles:
    - certbot
    - nginx
    - resolv
    - znc
