---
- name: apply configuration to all nodes
  hosts: all
  become: yes
  gather_facts: no
  roles:
    ## environment
    - apt
    - common
    - journald
    - resolv
    - ufw
    - users
    ## compilers/runtimes
    - docker
    - elm
    - erlang
    - haskell
    - julia
    - nodejs
    - perl
    - php
    - python
    - rust
    #- ziglang
    ## tools/apps
    - aws
    - google-cloud
    - neovim
    - protobuf
    - universal-ctags

- name: apply configuration to laptop
  hosts: laptop
  become: yes
  gather_facts: no
  roles:
    - desktop
    - fonts

- name: apply configuration to development
  hosts: development
  become: yes
  gather_facts: no
  roles:
    - grub

- name: apply configuration to production
  hosts: production
  become: yes
  gather_facts: no
  roles:
    - certbot
    - nginx
    - znc
