---
- name: fcitx packages
  apt:
    name:
      - fcitx
      - fcitx-frontend-all
      - fcitx-mozc

- name: set fcitx as system-wide im
  vars:
    im: fcitx
  block:
    - template:
        src: environment.j2
        dest: /etc/environment
        mode: "0644"
