---
- name: fcitx packages
  apt:
    name:
      - fcitx
      - fcitx-frontend-all
      - fcitx-mozc

- name: ibus packages
  apt:
    name:
      - ibus
      - ibus-mozc
    state: absent

- name: uim packages
  apt:
    name:
      - uim
      - uim-mozc
    state: absent

- name: system-wide desktop environment
  copy:
    src: environment/99-fcitx.conf
    dest: /etc/environment.d/99-fcitx.conf
    mode: "0644"
