- name: check installed yowcow-i3blocks version
  shell:
    cmd: "dpkg-query -W yowcow-i3blocks 2>/dev/null | awk '{ print $2 }'"
  register: installed_revision

- name: install yowcow-i3blocks
  when: installed_revision.stdout.find(yowcow_i3blocks.revision) == -1
  block:
    - apt:
        deb: "https://github.com/yowcow/i3blocks-deb/releases/download/{{ yowcow_i3blocks.revision }}/yowcow-i3blocks_{{ yowcow_i3blocks.revision }}_amd64.deb"
