---
- name: install desktop packages
  apt:
    name:
      - acpi
      - darktable
      - pavucontrol
      - ranger
      - vlc

- name: system-wide locale
  copy:
    src: locale
    dest: /etc/default/locale
    mode: "0644"

- include: backlight.yml
- include: ctrl-nocaps.yml
- include: fonts.yml
#- include: wine.yml

# desktops
- include: gnome.yml
- include: i3.yml
- include: sway.yml

# im
#- include: ibus-mozc.yml
#- include: fcitx-mozc.yml
- include: fcitx5-mozc.yml
