---
- name: install desktop packages
  apt:
    name:
      - acpi
      - gimp
      - mesa-utils
      - pavucontrol
      - ranger
      - vlc
      - weston

- name: system-wide locale
  copy:
    src: locale
    dest: /etc/default/locale
    mode: "0644"

- include_tasks: backlight.yml
- include_tasks: ctrl-nocaps.yml
- include_tasks: fonts.yml
#- include_tasks: wine.yml

# desktops
- include_tasks: gnome.yml

# im
- include_tasks: fcitx5.yml

# environment
- name: set desktop profile
  vars:
    im: fcitx5
  block:
    - template:
        src: environment.d/99desktop.conf.j2
        dest: /etc/environment.d/99desktop.conf
        mode: "0644"
