---
- name: install desktop packages
  apt:
    name:
      - acpi
      - darktable
      - pavucontrol
      - ranger
      - vlc

- name: system-wide locale
  copy:
    src: locale
    dest: /etc/default/locale
    mode: "0644"

- include_tasks: backlight.yml
- include_tasks: ctrl-nocaps.yml
- include_tasks: fonts.yml
#- include_tasks: wine.yml

# desktops
- include_tasks: gnome.yml
- include_tasks: i3.yml
- include_tasks: sway.yml

# im
#- include_tasks: ibus-mozc.yml
#- include_tasks: fcitx-mozc.yml
- include_tasks: fcitx5-mozc.yml
