---
- name: install desktop packages
  apt:
    name:
      - acpi
      - pavucontrol
      - ranger
      - vlc

- name: system-wide locale
  copy:
    src: locale
    dest: /etc/default/locale
    mode: "0644"

- name: system-wide desktop environment
  copy:
    src: environment
    dest: /etc/environment
    mode: "0644"

- include: alacritty.yml
- include: backlight.yml
- include: ctrl-nocaps.yml
- include: fonts.yml
- include: gnome.yml
#- include: regolith.yml
#- include: i3.yml
#- include: mozc.yml
- include: sway.yml
#- include: wine.yml
