---
- name: install packages for sway
  apt:
    name:
      - blueman
      - brightnessctl
      - kanshi
      - suckless-tools
      - sway
      - sway-backgrounds
      - swaybg
      - swayidle
      - swaylock
      - waybar
      - wdisplays
      - wofi
