# https://llandy3d.github.io/sway-on-ubuntu/simple_install/#build-wlroots
- name: install packages to build sway
  apt:
    name:
      - libcairo2-dev
      - libgdk-pixbuf2.0-dev
      - libjson-c-dev
      - libpango1.0-dev
      - meson
      - ninja-build
      - scdoc

- name: install packages to build wlroots
  apt:
    name:
      - cmake
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libdrm-dev
      - libegl1-mesa-dev
      - libgbm-dev
      - libgles2-mesa-dev
      - libgudev-1.0-dev
      - libinput-dev
      - libpixman-1-dev
      - libpng-dev
      - libsystemd-dev
      - libwayland-dev
      - libxcb-dri3-dev
      - libxcb-present-dev
      - libxcb-render-util0-dev
      - libxcb-res0-dev
      - libxkbcommon-dev
      - meson
      - ninja-build
      - wayland-protocols
      - xwayland
