- name: install apt packages
  apt:
    name:
      - apt-file
      - apt-transport-https
      - ca-certificates
      - gnupg
      - software-properties-common

- include_tasks: darktable.yml
- include_tasks: hashicorp.yml
- include_tasks: google-cloud-sdk.yml

- name: update apt cache
  apt:
    update_cache: yes

- name: update apt-file cache
  command:
    cmd: apt-file update
