- name: lsb_release -sc
  shell:
    cmd: "lsb_release -sr 2>/dev/null | tr -d '\n'"
  register: lsb_release

- name: check installed yowcow-erlang version
  shell:
    cmd: "dpkg-query -W yowcow-erlang 2>/dev/null | awk '{ print $2 }'"
  register: installed_revision

- name: install yowcow-erlang
  when: installed_revision.stdout.find(yowcow_erlang.revision) == -1
  block:
    - apt:
        deb: "https://github.com/yowcow/erlang-deb/releases/download/{{ yowcow_erlang.revision }}/yowcow_erlang-{{ yowcow_erlang.revision }}.ubuntu{{ lsb_release.stdout }}.amd64.deb"

- include_tasks: rebar3.yml
- include_tasks: erlgrind.yml
