- name: check installed erlang version
  shell:
    cmd: "dpkg-query -W erlang 2>/dev/null | awk '{ print $2 }'"
  register: installed_revision

- name: install erlang
  when: installed_revision.stdout.find(erlang.revision) == -1
  block:
    - apt:
        deb: "https://github.com/yowcow/erlang-deb/releases/download/{{ erlang.revision }}/erlang_{{ erlang.revision }}_amd64.deb"

- include: rebar3.yml
