---
- name: install packages for bluetooth
  apt:
    name:
      - blueman
      - bluez
      - bluez-tools
      - pipewire

      #- gstreamer1.0-plugins-bad
      #- libspa-0.2-bluetooth
      #- pulseaudio-module-bluetooth
