---
- name: install darktable deps
  apt:
    name:
      - libcurl4-gnutls-dev
      - libexiv2-dev
      - libimage-exiftool-perl
      - libimath-dev
      - libjson-glib-dev
      - liblcms2-dev
      - liblensfun-dev
      - libpugixml-dev
      - libsqlite3-dev
      - python3-imath
      - python3-jsonschema
      - xsltproc
      - libavif-dev
      - libcolord-dev
      - libcolord-gtk-dev
      - libcups2-dev
      - libgmic-dev
      - libgphoto2-dev
      - libgraphicsmagick1-dev
      - libheif-dev
      - libjxl-dev
      - libopenexr-dev
      - libopenjp2-7-dev
      - libosmgpsmap-1.0-dev
      - libsdl2-dev
      - libsecret-1-dev

- name: lsb_release -sr
  shell:
    cmd: "lsb_release -sr 2>/dev/null | tr -d '\n'"
  register: lsb_release

- name: check installed yowcow-darktable version
  shell:
    cmd: "dpkg-query -W yowcow-darktable 2>/dev/null | cut -f2"
  register: installed_revision

- name: install yowcow-darktable
  when: installed_revision.stdout.find(yowcow_darktable.revision) == -1
  block:
    - apt:
        deb: "https://github.com/yowcow/darktable-deb/releases/download/{{ yowcow_darktable.revision }}/yowcow-darktable.{{ yowcow_darktable.revision }}.ubuntu-{{ lsb_release.stdout }}.amd64.deb"
