---
- name: lsb_release -sr
  shell:
    cmd: "lsb_release -sr 2>/dev/null | tr -d '\n'"
  register: lsb_release

- name: check installed yowcow-darktable version
  shell:
    cmd: "dpkg-query -W yowcow-darktable 2>/dev/null | cut -f2"
  register: installed_revision

- name: install yowcow-darktable
  when: installed_revision.stdout.find(yowcow_darktable.revision) == -1
  block:
    - apt:
        deb: "https://github.com/yowcow/darktable-deb/releases/download/{{ yowcow_darktable.revision }}/yowcow-darktable.{{ yowcow_darktable.revision }}.ubuntu-{{ lsb_release.stdout }}.amd64.deb"
