- name: install packages for python3
  apt:
    name:
      - python3
      - python3-dev
      - python3-doc
      - python3-pip

- name: install packages for python2
  apt:
    name:
      - python2
      - python2-dev
      - python2-doc

- name: symlink python to python2.7
  file:
    src: /usr/bin/python2.7
    dest: /usr/local/bin/python
    state: link
