- name: check installed aws-cli revision
  shell:
    cmd: "(aws --version | awk '{ print $1 }' || true) 2>/dev/null"
  register: installed_revision

- name: check latest aws-cli release
  uri:
    url: https://api.github.com/repos/aws/aws-cli/tags
    method: GET
    return_content: yes
  register: latest_revision

- name: fetch and install aws-cli
  when: installed_revision.stdout.find(latest_revision.json[0].name) == -1
  block:
    - file:
        path: "{{ aws_cli.src }}/awscli-{{ latest_revision.json[0].name }}"
        state: directory
        mode: "0755"
    - get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ latest_revision.json[0].name }}.zip"
        dest: "{{ aws_cli.src }}/awscli-{{ latest_revision.json[0].name }}.zip"
        mode: "0644"
    - unarchive:
        src: "{{ aws_cli.src }}/awscli-{{ latest_revision.json[0].name }}.zip"
        dest: "{{ aws_cli.src }}/awscli-{{ latest_revision.json[0].name }}"
    - shell:
        chdir: "{{ aws_cli.src }}/awscli-{{ latest_revision.json[0].name }}"
        cmd: "(which aws && ./aws/install --update) || ./aws/install"

- name: clean-up old src files
  command: "find {{ aws_cli.src }} -maxdepth 1 -ctime +30 -exec rm -rf {} \\;"

- name: check current installations
  shell:
    cmd: "readlink -f /usr/local/aws-cli/v2/current"
  register: current_install

- name: clean-up old installations
  command: "find /usr/local/aws-cli/v2 -mindepth 1 -maxdepth 1 -type d -not -path '{{ current_install.stdout }}' -exec rm -rf {} \\;"
