- name: check installed awscli revision
  shell:
    cmd: "(aws --version | awk '{ print $1 }' || true) 2>/dev/null"
  register: installed_revision

- name: fetch and install awscli
  when: installed_revision.stdout.find(awscli.revision) == -1
  block:
    - file:
        path: "{{ awscli.src }}/awscli-{{ awscli.revision }}"
        state: directory
        mode: "0755"
    - get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ awscli.revision }}.zip"
        dest: "{{ awscli.src }}/awscli-{{ awscli.revision }}.zip"
        mode: "0644"
    - unarchive:
        src: "{{ awscli.src }}/awscli-{{ awscli.revision }}.zip"
        dest: "{{ awscli.src }}/awscli-{{ awscli.revision }}"
    - shell:
        chdir: "{{ awscli.src }}/awscli-{{ awscli.revision }}"
        cmd: "(which aws && ./aws/install --update) || ./aws/install"
