- name: install packages for ufw
  apt:
    name:
      - ufw

- name: enable UFW with default policy
  ufw:
    default: "{{ ufw.default }}"
    logging: "{{ ufw.logging }}"
    state: enabled

- name: apply UFW rules
  with_items: "{{ ufw.rules }}"
  ufw:
    to_port: "{{ item.to_port }}"
    rule: "{{ item.rule }}"
