- name: install packages for certbot
  apt:
    name:
      - certbot

#- name: install certbot crontab
#  copy:
#    src: crontab/certbot
#    dest: /etc/cron.daily/certbot
#    mode: "0755"

- name: install certbot logrotate
  copy:
    src: logrotate/certbot
    dest: /etc/logrotate.d/certbot
    mode: "0644"
