- name: check installed v language revision
  shell:
    cmd: "(v --version | cut -d' ' -f2 | sed 's/\\.0$//' || true) 2>/dev/null"
  register: installed_revision

- name: build and install v language
  when: installed_revision.stdout != v.revision
  block:
    - git:
        repo: https://github.com/vlang/v.git
        dest: "{{ v.src }}"
        version: "{{ v.revision }}"
    - shell:
        chdir: "{{ v.src }}"
        cmd: make
    - shell:
        chdir: "{{ v.src }}"
        cmd: ./v symlink
