- name: set time zone
  file:
    src: /usr/share/zoneinfo/Asia/Tokyo
    dest: /etc/localtime
    state: link
    force: yes

- name: install packages
  apt:
    name:
      - apache2-utils
      - autoconf
      - automake
      - bind9-dnsutils
      - bison
      - build-essential
      - ca-certificates
      - checkinstall
      - clang
      - cmake
      - crossbuild-essential-arm64
      - curl
      - devscripts
      - dpkg-dev
      - equivs
      - finger
      - flex
      - g++
      - gawk
      - git
      - gnupg-agent
      - gnupg2
      - golang
      - gpg
      - htop
      - jq
      - links
      - lua5.4
      - lynx
      - man
      - meson
      - ncal
      - netbase
      - nsnake
      - parallel
      - pinentry-tty
      - pkg-config
      - ripgrep
      - rsync
      - ruby
      - ruby-dev
      - software-properties-common
      - speedtest-cli
      - tmpreaper
      - tmux
      - traceroute
      - tree
      - tzdata
      - uuid-runtime
      - valgrind
      - weechat
      - whois
      - zip
      - zsh

- name: install apt lib packages
  apt:
    name:
      - libdb-dev
      - libxml2-dev
      - libxml2-utils

- name: install packages for AppImage support
  apt:
    name:
      - libfuse2

- name: install basic fonts
  apt:
    name:
      - fonts-freefont-ttf
      - fonts-liberation
      - fonts-noto

- name: install pdf utilities
  apt:
    name:
      - poppler-utils

- name: install 3rd-party packages
  apt:
    name:
      - google-cloud-sdk
      - terraform
      - terraform-ls

- include_tasks: flatpak.yml
- include_tasks: mysql.yml
- include_tasks: psql.yml
- include_tasks: snap.yml
- include_tasks: sysstat.yml
