- name: set time zone
  file:
    src: /usr/share/zoneinfo/Asia/Tokyo
    dest: /etc/localtime
    state: link
    force: yes

- name: install packages
  apt:
    name:
      - apache2-utils
      - apt-transport-https
      - autoconf
      - automake
      - bind9-dnsutils
      - bison
      - build-essential
      - ca-certificates
      - checkinstall
      - clang
      - cmake
      - cronolog
      - curl
      - devscripts
      - equivs
      - finger
      - flex
      - g++
      - gawk
      - git
      - gnupg-agent
      - gnupg2
      - golang
      - gpg
      - htop
      - jq
      - links
      - lua5.4
      - lynx
      - man
      - ncal
      - netbase
      - netcat
      - pinentry-tty
      - pkg-config
      - ripgrep
      - rsync
      - ruby
      - ruby-dev
      - software-properties-common
      - speedtest-cli
      - sqlite3
      - sqlite3-doc
      - sqlite3-pcre
      - tmpreaper
      - tmux
      - traceroute
      - tree
      - tzdata
      - uuid-runtime
      - valgrind
      - weechat
      - whois
      - zip
      - zsh

- name: install apt lib packages
  apt:
    name:
      - libdb-dev
      - libxml2-dev
      - libxml2-utils

- name: install basic fonts
  apt:
    name:
      - fonts-freefont-ttf
      - fonts-liberation
      - fonts-noto

- include: mysql.yml
- include: psql.yml
- include: snap.yml
- include: sysstat.yml
