- name: create docker plugin directory
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory

- name: create docker config directory
  file:
    path: /etc/docker
    state: directory

- name: store docker global config
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

#- include: docker-ce.yml
- include: docker-io.yml
- include: docker-buildx.yml
- include: docker-compose.yml
