---
- name: lsb_release -sc
  shell:
    cmd: "lsb_release -sr 2>/dev/null | tr -d '\n'"
  register: lsb_release

- name: check installed yowcow-wlroots version
  shell:
    cmd: "dpkg-query -W yowcow-wlroots 2>/dev/null | cut -f2"
  register: installed_revision

- name: install yowcow-wlroots
  when: installed_revision.stdout.find(yowcow_sway.revision.wlroots) == -1
  block:
    - apt:
        deb: "https://github.com/yowcow/swaywm-deb/releases/download/{{ yowcow_sway.revision.sway }}/yowcow-wlroots.{{ yowcow_sway.revision.wlroots }}.ubuntu-{{ lsb_release.stdout }}.amd64.deb"

- name: check installed yowcow-sway version
  shell:
    cmd: "dpkg-query -W yowcow-sway 2>/dev/null | cut -f2"
  register: installed_revision

- name: install yowcow-sway
  when: installed_revision.stdout.find(yowcow_sway.revision.sway) == -1
  block:
    - apt:
        deb: "https://github.com/yowcow/swaywm-deb/releases/download/{{ yowcow_sway.revision.sway }}/yowcow-sway.{{ yowcow_sway.revision.sway }}.ubuntu-{{ lsb_release.stdout }}.amd64.deb"

- include_tasks: sway-util.yml
- include_tasks: sway-autotiling.yml
