- name: install pip3 packages for i3ipc
  apt:
    name:
      - python3-i3ipc

- name: fetch autotiling executable
  get_url:
    url: https://raw.githubusercontent.com/nwg-piotr/autotiling/master/autotiling/main.py
    dest: /usr/local/bin/autotiling
    mode: "0755"
