- name: install pip3 packages for i3
  pip:
    name:
      - i3ipc
    executable: pip3
    state: latest

- name: fetch autotiling executable
  get_url:
    url: https://raw.githubusercontent.com/nwg-piotr/autotiling/master/autotiling/main.py
    dest: /usr/local/bin/autotiling
    mode: "0755"
