- name: install packages for universal-ctags
  apt:
    name:
      - gcc
      - make
      - pkg-config
      - autoconf
      - automake
      - python3-docutils
      - libseccomp-dev
      - libjansson-dev
      - libyaml-dev
      - libxml2-dev

- name: check if ctags already installed
  stat:
    path: /opt/universal-ctags/bin/ctags
  register: stat_result

- name: build and install universal-ctags
  when: not stat_result.stat.exists
  vars:
    src: /opt/src/universal-ctags
    prefix: /opt/universal-ctags
  block:
    - git:
        repo: https://github.com/universal-ctags/ctags.git
        dest: "{{ src }}"
    - shell:
        chdir: "{{ src }}"
        cmd: ./autogen.sh
    - shell:
        chdir: "{{ src }}"
        cmd: "./configure --prefix={{ prefix }}"
    - make:
        chdir: "{{ src }}"
        target: clean
    - make:
        chdir: "{{ src }}"
        target: all
    - make:
        chdir: "{{ src }}"
        target: install

- name: symlink ctags
  file:
    src: /opt/universal-ctags/bin/ctags
    dest: /usr/local/bin/ctags
    state: link

- name: symlink readtags
  file:
    src: /opt/universal-ctags/bin/readtags
    dest: /usr/local/bin/readtags
    state: link
