---
# Fiding default fonts:
#   * fonts for "sans": `fc-match sans`
#   * fonts for "sans" in ja: `fc-match sans:lang=ja`
#   * fonts for "DejaVu.ttf": `fc-match -a "DejaVu Sans" | less`

- name: install font packages
  apt:
    name:
      - fonts-dejavu
      - fonts-firacode
      - fonts-font-awesome
      - fonts-hack
      - fonts-liberation
      - fonts-liberation2
      - fonts-noto
      - fonts-noto-hinted

#
# `fc-list` to find font names
#
- include: ibm-plex.yml
- include: jetbrains-mono.yml
- include: nerd-fonts.yml
- include: pt-mono.yml
