- name: Create /usr/local/share/fonts/pt-mono
  file:
    path: /usr/local/share/fonts/pt-mono
    state: directory

- name: Check if PT Mono font is installed
  stat:
    path: /usr/local/share/fonts/pt-mono/PTMono-Regular.ttf
  register: stat_result

- name: Install PT Mono font if not installed
  when: not stat_result.stat.exists
  block:
    - copy:
        src: fonts/PT_Mono.zip
        dest: /tmp/PT_Mono.zip
    - ansible.builtin.unarchive:
        src: /tmp/PT_Mono.zip
        dest: /usr/local/share/fonts/pt-mono
        remote_src: yes
    - command: fc-cache
